using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Logic_Pipes
{
    public partial class Fileselect : Form
    {
        public Fileselect()
        {
            InitializeComponent();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrWhiteSpace(fileBox.Text) || !fileBox.Text.EndsWith(".lpp"))
                MessageBox.Show("Enter a .lpp file to create", "Error", MessageBoxButtons.OK);
            else
            {
                Dialogue.Message("I'll create a new lpproperties file at " + fileBox.Text + ".");
                System.IO.File.WriteAllLines(fileBox.Text, new string[]
                {
                    "###DO NOT EDIT THIS FILE!!!!!!!!###",
                    fileBox.Text
                });
                Global.Path = fileBox.Text;
                Dialogue.Message("Done!");
                Global.Continue = true;
                Close();
            }
        }
        private void button1_Click(object sender, EventArgs e)
        {
            openLppDialogue.ShowDialog();
            if(openLppDialogue.FileName != "openFileDialog1") fileBox.Text = openLppDialogue.FileName;
        }

        private void confirm_Click(object sender, EventArgs e)
        {
            if (!string.IsNullOrEmpty(fileBox.Text))
            {
                Dialogue.Message("Hey, " + fileBox.Text + ", are you there?");
                if (System.IO.File.Exists(fileBox.Text))
                {
                    Dialogue.Message("Why, yes I am!");
                    Dialogue.Message("Are you a logic pipe properties file?");
                    if (!fileBox.Text.EndsWith(".lpp"))
                    {
                        MessageBox.Show("Not a .lpp file", "Error", MessageBoxButtons.OK);
                        Dialogue.Message("No, sorry.");
                        Dialogue.Error("The file I found wasn't a lpp file!");
                    }
                    else
                    {
                        Dialogue.Message("Yes!");
                        Dialogue.Message("Do you have the right contents?");
                        string fl = null;
                        bool c = false;
                        try { fl = System.IO.File.ReadAllLines(fileBox.Text)[0]; c = true; } catch (IndexOutOfRangeException) { }
                        if (c && fl.StartsWith("###"))
                        {
                            Dialogue.Message("Yes!");
                            Dialogue.Message("I have found my file!");
                            Global.Path = fileBox.Text;
                            Global.Continue = true;
                            Close();
                        }
                        else
                        {
                            Dialogue.Message("No, sorry.");
                            Dialogue.Message("I'll put them in, then.");
                            System.IO.File.WriteAllLines(fileBox.Text, new string[]
                            {
                            "###DO NOT EDIT THIS FILE!!!!!!!!###",
                            fileBox.Text
                            });
                            Dialogue.Message("Done!");
                            Global.Path = fileBox.Text;
                            Global.Continue = true;
                            Close();
                        }
                    }
                }
                else
                {
                    Dialogue.Message("...I guess not.");
                    MessageBox.Show("File not found", "Error", MessageBoxButtons.OK);
                    Dialogue.Error("I couldn't find the file!");
                }
            }
        }
    }
}
